BaseUrl= "http://www.crushingcode.co"
languageCode = "en-us"
Title= "Crushing C.O.D.E"
paginate = 5
DisqusShortname = "nisrulz"
Copyright = "All rights reserved - 2015"
canonifyurls = true
theme = "casper"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/"
  weight = -120
[[menu.main]]
  name = "Github"
  pre = "<b>Follow me<b>"
  url = "https://github.com/nisrulz"
  weight = 100
[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/nisrulz"
  weight = 101
[[menu.main]]
  name = "Dribbble"
  url = "https://dribbble.com/nisrulz"
  weight = 102
[[menu.main]]
  name = "About.me"
  pre = "<b>Contact Me</b>"
  url = "https://about.me/nisrulz"
  weight = 109

[params]
  description = "43 72 75 73 68 69 6e 67 20 43 2e 4f 2e 44 2e 45"
  cover = "images/cover3.jpeg"
  author = "Nishant Srivastava"
  authorlocation = "Gurgaon, India"
  authorwebsite = "https://about.me/nisrulz"
  bio= "Creative sleeper. Avid dreamer."
  logo = "images/author.jpg"
  comments = true
  googleAnalyticsUserID = "UA-79101-12"
  githubName = "nisrulz"
  twitterName = "nisrulz"
  facebookName = "NishantRulez"
  linkedinName = "nisrulz"
  googlePlusName = "NishantSrivastava26"
  pinterestName = "nisrulz"
  instagramName = "nisrulz"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
[permalinks]
  post = "/:slug/"
[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"
